"""empty message

Revision ID: 40494e847f3b
Revises: b9ea9214360b
Create Date: 2025-01-24 17:27:15.285159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40494e847f3b'
down_revision = 'b9ea9214360b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('initialised',
    sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('pk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('initialised')
    # ### end Alembic commands ###
