"""empty message

Revision ID: 40737d55ba5a
Revises: 1383f2331acf
Create Date: 2025-01-15 12:01:26.401492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40737d55ba5a'
down_revision = '1383f2331acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automations',
    sa.Column('automationId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deviceId', sa.Integer(), nullable=False),
    sa.Column('dateTime', sa.DateTime(), nullable=False),
    sa.Column('newState', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['deviceId'], ['iot_devices.deviceId'], ),
    sa.PrimaryKeyConstraint('automationId')
    )
    with op.batch_alter_table('energy_saving_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))

    with op.batch_alter_table('iot_devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unlocked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iot_devices', schema=None) as batch_op:
        batch_op.drop_column('unlocked')

    with op.batch_alter_table('energy_saving_goals', schema=None) as batch_op:
        batch_op.drop_column('date')

    op.drop_table('automations')
    # ### end Alembic commands ###
