"""empty message

Revision ID: 92cc03c6a675
Revises: 231e21ef8020
Create Date: 2025-01-09 21:22:35.119776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92cc03c6a675'
down_revision = '231e21ef8020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('energy_records',
    sa.Column('energyRecordId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('energyUse', sa.Integer(), nullable=False),
    sa.Column('energyGeneration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('energyRecordId')
    )
    op.create_table('energy_saving_goals',
    sa.Column('goalId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('goalId')
    )
    op.create_table('iot_device',
    sa.Column('deviceId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('Operating', 'Fault', name='iotstate'), nullable=False),
    sa.Column('pinCode', sa.String(length=4), nullable=True),
    sa.Column('uptimeTimestamp', sa.DateTime(), nullable=True),
    sa.Column('logPath', sa.String(length=200), nullable=True),
    sa.Column('ipAddress', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('deviceId'),
    sa.UniqueConstraint('ipAddress'),
    sa.UniqueConstraint('logPath'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag',
    sa.Column('tagId', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('tagId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag')
    op.drop_table('iot_device')
    op.drop_table('energy_saving_goals')
    op.drop_table('energy_records')
    # ### end Alembic commands ###
