"""empty message

Revision ID: b9ea9214360b
Revises: 40737d55ba5a
Create Date: 2025-01-24 14:41:42.545396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ea9214360b'
down_revision = '40737d55ba5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iot_device_usage',
    sa.Column('deviceUsageId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('usage', sa.Integer(), nullable=False),
    sa.Column('deviceId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deviceId'], ['iot_devices.deviceId'], ),
    sa.PrimaryKeyConstraint('deviceUsageId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('iot_device_usage')
    # ### end Alembic commands ###
